version: '3'
services:
  react-app:
    container_name: react-js
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=${APP_NAME}
    volumes:
      - "./${APP_NAME}:/usr/src/app"
      - /usr/src/app/node_modules
    expose:
      - 3000
    ports:
      - "${APP_PORT}:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true.
